PACKAGE_NAME="dell-ir-camera"
PACKAGE_VERSION="0.1"
MAKE[0]="make KVER=$kernelver"
BUILT_MODULE_NAME[0]="og0ve1b"
DEST_MODULE_LOCATION[0]="/updates/dkms"
BUILT_MODULE_NAME[1]="ipu-bridge"
DEST_MODULE_LOCATION[1]="/updates/dkms"
AUTOINSTALL="yes"
